[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']

[tool.isort]
profile = "black"
py_version = 39
line_length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = "E203,W503"

[tool.mypy]
python_version = "3.9"
warn_return_any = true
ignore_missing_imports = true
