name: Publish Medium Blog

on:
  schedule:
    - cron: "30 8 * * *"  # 8:30 AM EST
  workflow_dispatch:

jobs:
  publish-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load secrets
        env:
          MEDIUM_INTEGRATION_TOKEN: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}
          MEDIUM_USER_ID: ${{ secrets.MEDIUM_USER_ID }}
        run: |
          python scripts/publish_medium_post.py --mode blog
