name: Daily Reddit Scrape

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM UTC
  workflow_dispatch: # Optional: allows you to run manually too

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Reddit Scraper
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GSPREAD_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GSPREAD_SERVICE_ACCOUNT_JSON }}
        run: python reddit_scraper.py
