name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Fetch all branches
        run: git fetch --all
      - name: Run Tests and Generate Coverage
        run: |
          pip install pytest pytest-cov pytest-asyncio
          pytest --cov=reddit_scraper --cov-report=xml
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=.
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.inclusions=reddit_scraper.py
